require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PickerExample' do
  config = use_native_modules!

  
  use_react_native!(:path => '../../node_modules/react-native', :hermes_enabled => false)



  pod 'RNCPicker', :path => '../../RNCPicker.podspec'

  target 'PickerExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end